# Generated by Django 5.2.6 on 2025-09-24 14:49

import apps.usuarios.models.PerfilUsuario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='apellido_materno',
            field=models.CharField(max_length=25, validators=[apps.usuarios.models.PerfilUsuario.validar_nombre_apellido]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='apellido_paterno',
            field=models.CharField(max_length=25, validators=[apps.usuarios.models.PerfilUsuario.validar_nombre_apellido]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='ci',
            field=models.CharField(max_length=7, validators=[apps.usuarios.models.PerfilUsuario.validar_ci]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(max_length=25, validators=[apps.usuarios.models.PerfilUsuario.validar_nombre_apellido]),
        ),
    ]
